spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Anurath@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: USERSERVICE

  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  config:
    import: "configserver:http://localhost:8086"


server:
  port: 8080

